ff_core:
    resource: "@FFCoreBundle/Resources/config/routing.yml"
    prefix:   /

ff_user:
    resource: "@FFUserBundle/Resources/config/routing.yml"
    prefix:   /

ff_fast:
    resource: "@FFFastBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
    
login:
    path: /login
    defaults:
        _controller: FFUserBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /logout