
security:
  encoders:
    FF\UserBundle\Entity\User: sha512

  role_hierarchy:
       ROLE_ADMIN:       [ROLE_CUISINIER]
        # On garde ce rôle superadmin, il nous resservira par la suite
       ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

  providers:
    main:
      id: fos_user.user_provider.username


  firewalls:
    main:
      pattern:      ^/
      anonymous:    true
      provider:   main
      form_login:
        login_path: fos_user_security_login
        check_path: fos_user_security_check
      logout:
        path:       fos_user_security_logout
        target:     fos_user_security_login
      remember_me:
         secret:     %secret% # %secret% est un paramètre de parameter    
  access_control:
    #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
