<?php

namespace FF\FastBundle\Repository;

/**
 * GammesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GammesRepository extends \Doctrine\ORM\EntityRepository
{
}
