<?php

namespace FF\FastBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;
/**
 * ProduitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitsRepository extends \Doctrine\ORM\EntityRepository
{
      public function findArray($array)
    {
        $qb = $this->createQueryBuilder('u')
                ->Select('u')
                ->Where('u.id IN (:array)')
                ->setParameter('array', $array);
        return $qb->getQuery()->getResult();
    }
      public function getProduits($page, $nbPerPage)
  {
    $query = $this->createQueryBuilder('a')
      ->orderBy('a.name')
      ->getQuery()
    ;

    $query
      // On définit l'annonce à partir de laquelle commencer la liste
      ->setFirstResult(($page-1) * $nbPerPage)
      // Ainsi que le nombre d'annonce à afficher sur une page
      ->setMaxResults($nbPerPage)
    ;

    // Enfin, on retourne l'objet Paginator correspondant à la requête construite
    // (n'oubliez pas le use correspondant en début de fichier)
    return new Paginator($query, true);
  }
  
  public function getProduitsByGamme($gamme, $page, $nbPerPage)
  {
    $query = $this->createQueryBuilder('a')
      ->orderBy('a.name')
      ->where('a.gammes = :gamme')
      ->setParameter('gamme', $gamme)
      ->getQuery()
    ;

    $query
      // On définit l'annonce à partir de laquelle commencer la liste
      ->setFirstResult(($page-1) * $nbPerPage)
      // Ainsi que le nombre d'annonce à afficher sur une page
      ->setMaxResults($nbPerPage)
    ;

    // Enfin, on retourne l'objet Paginator correspondant à la requête construite
    // (n'oubliez pas le use correspondant en début de fichier)
    return new Paginator($query, true);
  }
  
  public function getSearch($search ,$page, $nbPerPage)
  {
    $query = $this->createQueryBuilder('a')
      ->select('a')
      ->join('a.ingredients', 'i')
      ->orderBy('a.name')
      ->where('a.name LIKE :search')
      ->orwhere('a.description LIKE :search')
      ->orwhere('a.price LIKE :search')
      ->orwhere('i.name LIKE :search')
      ->setParameter('search', '%'.addcslashes($search, '%_').'%')
      ->getQuery()
    ;

    $query
      // On définit l'annonce à partir de laquelle commencer la liste
      ->setFirstResult(($page-1) * $nbPerPage)
      // Ainsi que le nombre d'annonce à afficher sur une page
      ->setMaxResults($nbPerPage)
    ;

    // Enfin, on retourne l'objet Paginator correspondant à la requête construite
    // (n'oubliez pas le use correspondant en début de fichier)
    return new Paginator($query, true);
  }
  
   public function getNb()
  {
    $query = $this->createQueryBuilder('a')
      ->select('COUNT(a) as nb , Identity(a.gammes) as id')
      ->orderBy('a.gammes')
      ->groupBy('a.gammes')
      ->getQuery()

    ;

    // Enfin, on retourne l'objet Paginator correspondant à la requête construite
    // (n'oubliez pas le use correspondant en début de fichier)
    return($query->getResult());
  } 
  
  public function getNbt()
  {
    $query = $this->createQueryBuilder('a')
      ->select('COUNT(a)')
      ->getQuery()
      ->getSingleScalarResult();

    ;

    // Enfin, on retourne l'objet Paginator correspondant à la requête construite
    // (n'oubliez pas le use correspondant en début de fichier)
    return($query);
  }
}




