ff_fast_homepage:
    path:     /home
    defaults: { _controller: FFFastBundle:Default:index }


ff_fast_home:
    path:     /gamme/home/{page}
    defaults: { _controller: FFFastBundle:Gammes:index, page :1 }
    requirements:
       id: \d+
ff_fast_view:
    path:      /gamme/{id}
    defaults:
       _controller: FFFastBundle:Gammes:view
    requirements:
       id: \d+

ff_fast_add:
    path:     /gammes/add
    defaults:
       _controller: FFFastBundle:Gammes:add

ff_fast_edit:
    path:     /gammes/edit/{id}
    defaults:
        _controller: FFFastBundle:Gammes:edit
    requirements:
       id: \d+

ff_fast_delete:
    path:      /gammes/delete/{id}
    defaults:
        _controller: FFFastBundle:Gammes:delete

ff_fast_homei:
    path:     /ingredient/home/{page}
    defaults: { _controller: FFFastBundle:Ingredients:index, page :1 }
    requirements:
        id: \d+
       
ff_fast_viewi:
    path:      /ingredient/view/{id}
    defaults:
       _controller: FFFastBundle:Ingredients:view
    requirements:
       id: \d+

ff_fast_addi:
    path:     /ingredient/add
    defaults:
       _controller: FFFastBundle:Ingredients:add

ff_fast_editi:
    path:     /ingredient/edit/{id}
    defaults:
        _controller: FFFastBundle:Ingredients:edit
    requirements:
       id: \d+

ff_fast_deletei:
    path:      /ingredient/delete/{id}
    defaults:
        _controller: FFFastBundle:Ingredients:delete

ff_fast_homep:
    path:     /produit/home/{page}
    defaults: { _controller: FFFastBundle:Produits:index, page:1 }

ff_fast_viewp:
    path:      /produit/{id}
    defaults:
       _controller: FFFastBundle:Produits:view
    requirements:
       id: \d+

ff_fast_addp:
    path:     /produit/add
    defaults:
       _controller: FFFastBundle:Produits:add

ff_fast_editp:
    path:     /produit/edit/{id}
    defaults:
        _controller: FFFastBundle:Produits:edit
    requirements:
       id: \d+

ff_fast_deletep:
    path:      /produit/delete/{id}
    defaults:
        _controller: FFFastBundle:Produits:delete
        
        
        
ff_fast_homepages:
    path:     /shop
    defaults: { _controller: FFFastBundle::index }
    
ff_fast_homes:
    path:     /shop/home/{page}
    defaults: { _controller: FFFastBundle:Shop:index, page :1 }
    requirements:
       id: \d+
       
ff_fast_gammes:
    path:     /shop/home/gamme/{gamme}/{page}
    defaults: { _controller: FFFastBundle:Shop:gamme, page :1 }
    requirements:
       gamme: \d+
      
       
ff_fast_views:
    path:     /shop/view/{id}
    defaults: { _controller: FFFastBundle:Shop:view }

