ff_fast_homepage:
    path:     /
    defaults: { _controller: FFFastBundle:Default:index }

ff_gammes_index:
    path:     /Gammes
    defaults: { _controller: FFFastBundle:Gammes:index }

ff_gammes_add:
    path:     /Gammes/add
    defaults: { _controller: FFFastBundle:Gammes:add }

ff_gammes_edit:
    path:     /Gammes/edit
    defaults: { _controller: FFFastBundle:Gammes:edit }